{
    "password":"",
    "accountAdvanceAccount":null,
    "address":"Lima central, calle 3",
    "additionalInformation": {
        "observations": "Observaciones del cliente.",
        "loggingFrequency":null,
        "alias":"",
        "typePaymentIds":[]
    },
    "cityId":null,
    "civilStatus":null,
    "contact":"",
    "countryId":null,
    "creditLimitDays":null,
    "customerType":"",
    "dateBirth":null,
    "discount":0,
    "email":"joserivas@gmail.com",
    "flagAccounting":null,
    "flagActive":true,
    "flagDetraction":null,
    "flagExemptTaxes":null,
    "flagItemsWithoutRetainer":null,
    "flagPostDatedCredit":null,
    "flagRelatedCustomer":null,
    "flagRetentionAgent":null,
    "flagSpecialContributor":null,
    "flagTypePerson":1,
    "gender":null,
    "geoPosition":"",
    "latitude":null,
    "limitAmountCredit":null,
    "longitude":null,
    "originIncomeId":null,
    "parishId":null,
    "paymentMethodId":null,
    "phone":"999888777",
    "phoneNumbers":["999888777"],
    "postalCode":"",
    "provinceId":null,
    "typeDestinationId":null,
    "zone":"",
    "dni":"00885566",
    "name":"jose Carlos ",
    "lastname":"rivas"
} 

